name: Tests

on: [push, pull_request]

jobs:
  test_go:
    name: Test Go
    strategy:
      matrix:
        go-version: ["1.20", "1.19", "1.18"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test -v -bench .
